# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-FixRemote
version:      0.01
version_from: lib/Apache2/FixRemote.pm
installdirs:  site
requires:
    Apache::Test:                  1.25
    mod_perl2:                     2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
